apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-storefront-ui
spec:
  params:
  - name: url
    value: https://github.com/ibm-cloud-architecture/devops-demo-storefront-ui
  - name: revision
    value: master
  type: git
